# Generated by Django 6.0.4 on 2026-04-27 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('exams', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('qualification', models.CharField(help_text='Highest qualification', max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of invigilation experience')),
                ('max_exams_per_day', models.PositiveIntegerField(default=3, help_text='Maximum exams per day')),
                ('is_available', models.BooleanField(default=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department')),
                ('preferred_venues', models.ManyToManyField(blank=True, to='venues.venue')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='InvigilatorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assignment', 'New Assignment'), ('reminder', 'Assignment Reminder'), ('cancellation', 'Assignment Cancellation'), ('update', 'Schedule Update'), ('general', 'General Notice')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='invigilators.invigilatorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvigilatorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('annual', 'Annual Leave'), ('personal', 'Personal Leave'), ('emergency', 'Emergency Leave'), ('training', 'Training Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='invigilators.invigilatorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvigilatorTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=200)),
                ('training_type', models.CharField(choices=[('basic', 'Basic Invigilation'), ('advanced', 'Advanced Techniques'), ('technology', 'Technology Systems'), ('emergency', 'Emergency Procedures'), ('other', 'Other')], default='basic', max_length=20)),
                ('training_date', models.DateField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('trainer', models.CharField(max_length=200)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='invigilator_certificates/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='invigilators.invigilatorprofile')),
            ],
            options={
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='InvigilatorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Performance rating (1-5 stars)')),
                ('punctuality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='good', max_length=20)),
                ('professionalism', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='good', max_length=20)),
                ('exam_conduct', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='good', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilator_evaluations', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_performances', to='exams.exam')),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='invigilators.invigilatorprofile')),
            ],
            options={
                'ordering': ['-evaluation_date'],
                'unique_together': {('invigilator', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='InvigilatorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='invigilators.invigilatorprofile')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('invigilator', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
