# Generated by Django 6.0.4 on 2026-04-27 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('seating', 'Seating Arrangement'), ('spacing', 'Student Spacing'), ('department_separation', 'Department Separation'), ('invigilator_workload', 'Invigilator Workload'), ('venue_preference', 'Venue Preference')], max_length=30)),
                ('description', models.TextField()),
                ('condition', models.JSONField(help_text='JSON condition for the rule')),
                ('action', models.JSONField(help_text='JSON action to apply when condition is met')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority rules are applied first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AllocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('auto_allocate', 'Auto Allocation'), ('manual_allocate', 'Manual Allocation'), ('modify_allocation', 'Modify Allocation'), ('cancel_allocation', 'Cancel Allocation'), ('reallocate', 'Reallocate')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_data', models.JSONField(blank=True, help_text='Previous allocation data', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='New allocation data', null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_logs', to='exams.exam')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExamAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_allocations', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_allocations', to=settings.AUTH_USER_MODEL)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='exams.exam')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_allocations', to='venues.venue')),
                ('venue_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.venuelayout')),
            ],
            options={
                'ordering': ['-allocation_date'],
            },
        ),
        migrations.CreateModel(
            name='AllocationConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('venue_overcapacity', 'Venue Overcapacity'), ('invigilator_double_booking', 'Invigilator Double Booking'), ('student_conflict', 'Student Conflict'), ('venue_unavailable', 'Venue Unavailable'), ('insufficient_invigilators', 'Insufficient Invigilators')], max_length=30)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='allocation.examallocation')),
            ],
            options={
                'ordering': ['-severity', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_data', models.JSONField(help_text='Complete seating plan data')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('exam_allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plan', to='allocation.examallocation')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='InvigilatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('chief', 'Chief Invigilator'), ('assistant', 'Assistant Invigilator'), ('support', 'Support Staff')], default='assistant', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('has_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilator_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('exam_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_assignments', to='allocation.examallocation')),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exam_allocation', '-is_primary', 'assignment_type'],
                'unique_together': {('exam_allocation', 'invigilator')},
            },
        ),
        migrations.CreateModel(
            name='StudentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('row_number', models.PositiveIntegerField()),
                ('column_number', models.PositiveIntegerField()),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('exam_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_allocations', to='allocation.examallocation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_seat_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exam_allocation', 'row_number', 'column_number'],
                'unique_together': {('exam_allocation', 'student')},
            },
        ),
    ]
