# Generated by Django 6.0.4 on 2026-04-27 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('venue_type', models.CharField(choices=[('lecture_hall', 'Lecture Hall'), ('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('auditorium', 'Auditorium'), ('multipurpose_hall', 'Multipurpose Hall'), ('outdoor', 'Outdoor Space')], default='lecture_hall', max_length=20)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=10)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of students')),
                ('exam_capacity', models.PositiveIntegerField(help_text='Maximum students for exams (usually less than capacity for spacing)')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Area in square meters', max_digits=8, null=True)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=False)),
                ('has_computers', models.BooleanField(default=False)),
                ('has_power_outlets', models.BooleanField(default=True)),
                ('is_wheelchair_accessible', models.BooleanField(default=False)),
                ('campus_location', models.CharField(help_text='e.g., Main Campus, City Campus', max_length=100)),
                ('gps_coordinates', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available_for_exams', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['building', 'floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VenueBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reason', models.CharField(max_length=200)),
                ('is_maintenance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='venues.venue')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VenueLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('layout_image', models.ImageField(blank=True, help_text='Image showing the seating layout', null=True, upload_to='venue_layouts/')),
                ('rows', models.PositiveIntegerField(help_text='Number of rows')),
                ('columns', models.PositiveIntegerField(help_text='Number of columns per row')),
                ('spacing_type', models.CharField(choices=[('standard', 'Standard Spacing'), ('wide', 'Wide Spacing'), ('social_distancing', 'Social Distancing')], default='standard', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='venues.venue')),
            ],
            options={
                'ordering': ['venue', 'name'],
                'unique_together': {('venue', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VenueRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 (Poor) to 5 (Excellent)')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='venues.venue')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('venue', 'user')},
            },
        ),
    ]
